### ISSUE TITLE
Why not DNS?

### ISSUE THREAD

**Issue by davwilliams** [bewilliams/internet_availability_monitor#1]
Looks great.  One thought to enhance the ping list is to allow FQDNs in ping_servers.conf.  This way you can account for IPs becoming deprecated for a given host.

**Comment by bewilliams** [comment]
I can, I just don't want to wrap DNS issues up with it.

**Comment by davwilliams** [comment]
I see what you're saying, but depending on the desired server list, IP alone may be unreliable.  For example, what if it's a dynamic IP.  Maybe the monitor can also test DNS resolution, too, as part of its monitoring feature.

**Comment by bewilliams** [comment]
You can provide a DNS name, if you'd like. It just passes that address directly to the ping command.  I would just rather use IP's because it eliminates issues with DNS.
